using System.Linq;
using System.Text;
using Content.Client.UserInterface.Controls;
using Content.Omu.Shared.PlantAnalyzer;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Omu.Client.PlantAnalyzer.UI;

[GenerateTypedNameReferences]
public sealed partial class PlantAnalyzerWindow : FancyWindow
{
    private const string IndentedNewline = "\n   ";

    public PlantAnalyzerWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void Populate(PlantAnalyzerScannedSeedMessage msg)
    {
        // flip visibility: hide placeholder, show tabs
        NoData.Visible = false;
        Tabs.Visible = true;

        // tabs 1 and 2 are only shown for advanced scans
        Tabs.SetTabVisible(1, msg.IsAdvanced);
        Tabs.SetTabVisible(2, msg.IsAdvanced);

        // ---- basic tab ----
        var nameKey = msg.IsTray
            ? "plant-analyzer-name-tray"
            : "plant-analyzer-name-seed";
        PlantName.Text = Loc.GetString(nameKey, ("name", Loc.GetString(
            string.IsNullOrEmpty(msg.SeedName) ? "plant-analyzer-unknown" : msg.SeedName)));

        PlantYield.Text = Loc.GetString("plant-analyzer-yield",
            ("value", $"{msg.SeedYield:D0}"));
        Potency.Text = Loc.GetString("plant-analyzer-potency",
            ("value", $"{msg.SeedPotency:F0}"));
        HarvestRepeat.Text = Loc.GetString("plant-analyzer-harvest",
            ("value", Loc.GetString($"plant-analyzer-harvest-{msg.HarvestType}")));

        Chemicals.Text = Loc.GetString("plant-analyzer-chemicals",
            ("value", BuildList(msg.Chemicals)));
        ConsumeGases.Text = Loc.GetString("plant-analyzer-consume-gases",
            ("value", BuildGasList(msg.ConsumeGases)));
        ExudeGases.Text = Loc.GetString("plant-analyzer-exude-gases",
            ("value", BuildGasList(msg.ExudeGases)));

        Lifespan.Text  = Loc.GetString("plant-analyzer-lifespan",   ("value", $"{msg.Lifespan:F1}"));
        Maturation.Text = Loc.GetString("plant-analyzer-maturation", ("value", $"{msg.Maturation:F1}"));
        Production.Text = Loc.GetString("plant-analyzer-production", ("value", $"{msg.Production:F1}"));
        GrowthStages.Text = Loc.GetString("plant-analyzer-growthstages", ("value", $"{msg.GrowthStages:D0}"));
        Endurance.Text = Loc.GetString("plant-analyzer-endurance",   ("value", $"{msg.Endurance:F0}"));

        if (!msg.IsAdvanced)
            return;

        // ---- tolerances tab ----
        NutrientUsage.Text   = Loc.GetString("plant-analyzer-tol-nutrient",      ("value", $"{msg.NutrientConsumption:F2}"));
        WaterUsage.Text      = Loc.GetString("plant-analyzer-tol-water",         ("value", $"{msg.WaterConsumption:F2}"));
        IdealHeat.Text       = Loc.GetString("plant-analyzer-tol-ideal-heat",    ("value", $"{msg.IdealHeat:F0}"));
        HeatTolerance.Text   = Loc.GetString("plant-analyzer-tol-heat-range",    ("value", $"{msg.HeatTolerance:F1}"));
        IdealLight.Text      = Loc.GetString("plant-analyzer-tol-ideal-light",   ("value", $"{msg.IdealLight:F1}"));
        LightTolerance.Text  = Loc.GetString("plant-analyzer-tol-light-range",   ("value", $"{msg.LightTolerance:F1}"));
        ToxinsTolerance.Text = Loc.GetString("plant-analyzer-tol-toxins",        ("value", $"{msg.ToxinsTolerance:F1}"));
        LowPressure.Text     = Loc.GetString("plant-analyzer-tol-low-pressure",  ("value", $"{msg.LowPressureTolerance:F1}"));
        HighPressure.Text    = Loc.GetString("plant-analyzer-tol-high-pressure", ("value", $"{msg.HighPressureTolerance:F1}"));
        PestTolerance.Text   = Loc.GetString("plant-analyzer-tol-pests",         ("value", $"{msg.PestTolerance:F1}"));
        WeedTolerance.Text   = Loc.GetString("plant-analyzer-tol-weeds",         ("value", $"{msg.WeedTolerance:F1}"));

        // ---- mutations tab ----
        var mutList = new StringBuilder();
        if (msg.Mutations == PlantMutationFlags.None)
        {
            mutList.Append(IndentedNewline);
            mutList.Append(Loc.GetString("plant-analyzer-mutations-none"));
        }
        else
        {
            if (msg.Mutations.HasFlag(PlantMutationFlags.TurnIntoKudzu))
            {
                mutList.Append(IndentedNewline);
                mutList.Append(Loc.GetString("plant-analyzer-mut-kudzu"));
            }
            if (msg.Mutations.HasFlag(PlantMutationFlags.Seedless))
            {
                mutList.Append(IndentedNewline);
                mutList.Append(Loc.GetString("plant-analyzer-mut-seedless"));
            }
            if (msg.Mutations.HasFlag(PlantMutationFlags.Ligneous))
            {
                mutList.Append(IndentedNewline);
                mutList.Append(Loc.GetString("plant-analyzer-mut-ligneous"));
            }
            if (msg.Mutations.HasFlag(PlantMutationFlags.CanScream))
            {
                mutList.Append(IndentedNewline);
                mutList.Append(Loc.GetString("plant-analyzer-mut-screaming"));
            }
        }
        Mutations.Text = Loc.GetString("plant-analyzer-mutations", ("value", mutList.ToString()));

        var specList = msg.Speciation.Length == 0
            ? IndentedNewline + Loc.GetString("plant-analyzer-speciation-none")
            : string.Concat(msg.Speciation.Select(s => IndentedNewline + Loc.GetString(s)));
        Speciation.Text = Loc.GetString("plant-analyzer-speciation", ("value", specList));
    }

    private static string BuildList(string[] items)
    {
        if (items.Length == 0)
            return " " + Loc.GetString("plant-analyzer-none");
        var sb = new StringBuilder();
        foreach (var item in items)
        {
            sb.Append(IndentedNewline);
            sb.Append(item);
        }
        return sb.ToString();
    }

    private static string BuildGasList(string[] gases)
    {
        if (gases.Length == 0)
            return " " + Loc.GetString("plant-analyzer-none");
        var sb = new StringBuilder();
        foreach (var gas in gases)
        {
            sb.Append(IndentedNewline);
            sb.Append(gas);
        }
        return sb.ToString();
    }
}
