using System.Linq;
using System.Text;
using Content.Client.UserInterface.Controls;
using Content.Shared._DV.PlantAnalyzer;
using Content.Shared.Botany;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._DV.PlantAnalyzer.UI;

[GenerateTypedNameReferences]
public sealed partial class PlantAnalyzerWindow : FancyWindow
{
    private const string IndentedNewline = "\n   ";

    private static readonly Color ColorGreen      = Color.FromHex("#7ecd48");
    private static readonly Color ColorLightGreen = Color.FromHex("#a8e070");
    private static readonly Color ColorYellow     = Color.FromHex("#f0c040");
    private static readonly Color ColorDarkYellow = Color.FromHex("#d4a830");
    private static readonly Color ColorCyan       = Color.FromHex("#4ecdc4");
    private static readonly Color ColorOrange     = Color.FromHex("#e8a837");
    private static readonly Color ColorRed        = Color.FromHex("#e05252");

    private const float HealthGoodPct = 66f;
    private const float HealthWarnPct = 33f;

    private const int YieldGoodCount = 8;
    private const int YieldOkCount   = 4;
    private const int YieldLowCount  = 2;

    private const float PotencyGoodPct = 80f;
    private const float PotencyOkPct   = 50f;
    private const float PotencyLowPct  = 20f;

    public PlantAnalyzerWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void Populate(PlantAnalyzerScannedSeedMessage msg)
    {
        NoData.Visible = false;
        Tabs.Visible = true;

        if (msg.IsTray && msg.IsDead)
        {
            DeadBanner.Visible = true;
            PlantName.FontColorOverride = ColorRed;
        }
        else
        {
            DeadBanner.Visible = false;
            PlantName.FontColorOverride = ColorGreen;
        }

        var nameKey = msg.IsTray ? "plant-analyzer-name-tray" : "plant-analyzer-name-seed";
        PlantName.Text = Loc.GetString(nameKey, ("name", Loc.GetString(
            string.IsNullOrEmpty(msg.SeedName) ? "plant-analyzer-unknown" : msg.SeedName)));

        if (msg.IsTray)
        {
            HealthRow.Visible = true;
            var pct = msg.PlantMaxHealth > 0f ? msg.PlantHealth / msg.PlantMaxHealth * 100f : 0f;
            PlantHealthLabel.Text = $"{msg.PlantHealth:F1} / {msg.PlantMaxHealth:F1}  ({pct:F1}%)";
            PlantHealthLabel.FontColorOverride = pct switch
            {
                > HealthGoodPct => ColorGreen,
                > HealthWarnPct => ColorOrange,
                _               => ColorRed,
            };
        }
        else
        {
            HealthRow.Visible = false;
        }

        HarvestRepeat.Text = Loc.GetString($"plant-analyzer-harvest-{msg.HarvestType}");
        HarvestRepeat.FontColorOverride = msg.HarvestType switch
        {
            HarvestType.Repeat      => ColorGreen,
            HarvestType.SelfHarvest => ColorCyan,
            _                       => ColorOrange,
        };

        PlantYield.Text    = $"{msg.SeedYield}";
        Potency.Text       = $"{msg.SeedPotency:F1}%";
        Lifespan.Text      = $"{msg.Lifespan:F1}";
        Maturation.Text    = $"{msg.Maturation:F1}";
        Production.Text    = $"{msg.Production:F1}";
        GrowthStages.Text  = $"{msg.GrowthStages}";
        Endurance.Text     = $"{msg.Endurance:F1}";

        PlantYield.FontColorOverride = msg.SeedYield switch
        {
            >= YieldGoodCount => ColorGreen,
            >= YieldOkCount   => ColorLightGreen,
            >= YieldLowCount  => ColorOrange,
            _                 => ColorRed,
        };

        Potency.FontColorOverride = msg.SeedPotency switch
        {
            >= PotencyGoodPct => ColorYellow,
            >= PotencyOkPct   => ColorDarkYellow,
            >= PotencyLowPct  => ColorOrange,
            _                 => ColorRed,
        };

        Chemicals.Text    = Loc.GetString("plant-analyzer-chemicals",     ("value", BuildList(msg.Chemicals)));
        ConsumeGases.Text = Loc.GetString("plant-analyzer-consume-gases", ("value", BuildList(msg.ConsumeGases)));
        ExudeGases.Text   = Loc.GetString("plant-analyzer-exude-gases",   ("value", BuildList(msg.ExudeGases)));

        NutrientUsage.Text   = $"{msg.NutrientConsumption:F1} u/stage";
        WaterUsage.Text      = $"{msg.WaterConsumption:F1} u/stage";
        IdealHeat.Text       = $"{msg.IdealHeat:F1} K";
        HeatTolerance.Text   = $"±{msg.HeatTolerance:F1} K";
        IdealLight.Text      = $"{msg.IdealLight:F1} cd";
        LightTolerance.Text  = $"±{msg.LightTolerance:F1} cd";
        ToxinsTolerance.Text = $"{msg.ToxinsTolerance:F1}";
        LowPressure.Text     = $"{msg.LowPressureTolerance:F1} kPa";
        HighPressure.Text    = $"{msg.HighPressureTolerance:F1} kPa";
        PestTolerance.Text   = $"{msg.PestTolerance:F1}";
        WeedTolerance.Text   = $"{msg.WeedTolerance:F1}";

        var mutText = msg.Mutations.Length == 0
            ? IndentedNewline + Loc.GetString("plant-analyzer-mutations-none")
            : BuildList(msg.Mutations);
        Mutations.Text = Loc.GetString("plant-analyzer-mutations", ("value", mutText));

        var specText = msg.Speciation.Length == 0
            ? IndentedNewline + Loc.GetString("plant-analyzer-speciation-none")
            : BuildList(msg.Speciation);
        Speciation.Text = Loc.GetString("plant-analyzer-speciation", ("value", specText));
    }

    private static string BuildList(string[] items)
    {
        if (items.Length == 0)
            return " " + Loc.GetString("plant-analyzer-none");
        var sb = new StringBuilder();
        foreach (var item in items)
        {
            sb.Append(IndentedNewline);
            sb.Append(item);
        }
        return sb.ToString();
    }
}
